#!/usr/bin/env node
VERSION = process.argv[2]
var util           = require('util')
,   exec           = require('child_process').exec
,   ios            = 'git://git.apache.org/incubator-cordova-ios.git'
,   blackberry     = 'git://git.apache.org/incubator-cordova-blackberry-webworks.git'
,   android        = 'git://git.apache.org/incubator-cordova-android.git'
,   windows        = 'git://git.apache.org/incubator-cordova-wp7.git'
,   webos          = 'git://git.apache.org/incubator-cordova-webos.git'
,   bada       	   = 'git://git.apache.org/incubator-cordova-bada.git'
,   docs      	   = 'git://git.apache.org/incubator-cordova-docs.git'
,	iosdir	       = 'incubator-cordova-ios'
,	blackberrydir  = 'incubator-cordova-blackberry-webworks'
,	androiddir	   = 'incubator-cordova-android'
,	windowsdir	   = 'incubator-cordova-wp7'
,	webosdir	   = 'incubator-cordova-webos'
,	badadir	       = 'incubator-cordova-bada'
,   docsdir        = 'incubator-cordova-docs'
, tempRepoDir     = 'temp/repositories'
, iosReleaseLibDir = ' ../../../release/lib/ios'
, blackberryReleaseLibDir = '../../../release/lib/blackberry'
, androidReleaseLibDir = '../../release/lib/android'
, androidReleaseLicense = '../../release/license'
, androidReleaseVersion = '../../release/version'
, windowsReleaseLibDir = '../../release/lib/windows'
, webosReleaseLibDir = '../../release/lib/webos'
, badaReleaseLibDir = '../../release/lib/bada'
, releaseDocDir = '../../release/doc'

var commandQueue = [],
    child;

function queueCommand(cmd) {
    commandQueue.push(cmd);
}

// Run through all queued commands in a synchronous manner.
// If there's an error it will stop executing commands.
// The callback parameter will fire once all commands have completed.
function executeCommands(callback) {
    var cmd = commandQueue.shift();
    if (cmd) {
		child = exec(cmd, function(err, stdout, stderr) {
        	if (err !== null) {
        		console.log('ERROR!' + err);
          		util.puts(stderr);
		  		executeCommands(callback);
        	} else {
          		util.puts(stdout);
          		executeCommands(callback);
        	}
		});
    	if (commandQueue.length === 0) {
    		// Attach the callback to the child since this is the last command.
    		child.on('exit', callback);
   		}
    } else {
    	console.log('All done');
    }
}

queueCommand("rm -rf temp && mkdir temp && cd temp && mkdir repositories && mkdir release");
queueCommand("cd temp/release && mkdir lib && cd lib && mkdir ios && mkdir android && mkdir blackberry && mkdir windows && mkdir webos && mkdir symbian && mkdir bada");

//ios
queueCommand("cd " + tempRepoDir + " && git clone "+ios+" && cd "+iosdir+" && git fetch --tags && git checkout "+VERSION);
queueCommand("cd " + tempRepoDir + "/"+iosdir+" && make");
queueCommand("cd " + tempRepoDir + "/"+iosdir+"/dist && cp -r PhoneGap-"+VERSION+".dmg " + iosReleaseLibDir + " && cp -r PhoneGap-"+VERSION+".dmg.SHA1 " + iosReleaseLibDir);

//blackberry
queueCommand("cd " + tempRepoDir + " && git clone "+blackberry+" && cd "+blackberrydir+" && git fetch --tags && git checkout "+VERSION);
queueCommand("cd " + tempRepoDir + "/"+blackberrydir+" && ant dist");
queueCommand("cd " + tempRepoDir + "/"+blackberrydir+"/dist && cp -r ./* " + blackberryReleaseLibDir);

//android
queueCommand("cd " + tempRepoDir + " && git clone "+android+" && cd "+androiddir+" && git fetch --tags && git checkout "+VERSION);
queueCommand("cd " + tempRepoDir + "/"+androiddir+" && cp LICENSE " + androidReleaseLicense + " && cp VERSION " + androidReleaseVersion + " && cp README.md " + androidReleaseLibDir);
queueCommand("cd " + tempRepoDir + "/"+androiddir+" && ./bin/create");
queueCommand("cd " + tempRepoDir + "/"+androiddir+" && cp -rp example" + androidReleaseLibDir + "/example");
queueCommand("cd " + tempRepoDir + "/"+androiddir+"/example && cp libs/phonegap-"+VERSION+".jar ../" + androidReleaseLibDir);
queueCommand("cd " + tempRepoDir + "/"+androiddir+"/example && cp assets/www/phonegap-"+VERSION+".js ../" + androidReleaseLibDir);

//windows phone
queueCommand("cd " + tempRepoDir + " && git clone "+windows+" && cd "+windowsdir+" && git fetch --tags && git checkout "+VERSION);
queueCommand("cd " + tempRepoDir + "/"+windowsdir+" && cp -r ./* " + windowsReleaseLibDir);

//webos
queueCommand("cd " + tempRepoDir + " && git clone "+webos+" && cd "+webosdir+" && git fetch --tags && git checkout "+VERSION);
queueCommand("cd " + tempRepoDir + "/"+webosdir+" && cp -r ./* " + webosReleaseLibDir);

//bada
queueCommand("cd " + tempRepoDir + " && git clone "+bada+" && cd "+badadir+" && git fetch --tags && git checkout "+VERSION);
queueCommand("cd " + tempRepoDir + "/"+badadir+" && cp -r ./* " + badaReleaseLibDir);

//docs
queueCommand("cd " + tempRepoDir + " && git clone "+docs+" && cd "+docsdir+" && git fetch --tags && git checkout "+VERSION);
queueCommand("cd " + tempRepoDir + "/"+docsdir+" && ./bin/phonegap-docs && cp -r public " + releaseDocDir);

//symbian is being depricated.


executeCommands(function(){
	exec("cd temp/release && git archive master -o phonegap-"+VERSION+".zip", function(e, stdout, stderr) {
	});
});
